name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make mvn executable
        run: chmod +x mvn

      - name: Install dependencies
        run: ./mvn install -DskipTests

      - name: Build the application
        run: ./mvn package -DskipTests

      - name: Display build message
        run: echo "Build of the application was successful!"
