name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: ./mvn install -DskipTests

      - name: Run tests
        run: ./mvn test
        continue-on-error: true

      - name: Build the application
        run: ./mvn package -DskipTests
        if: ${{ success() }}

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/Exercice6Spring-0.0.1-SNAPSHOT.jar

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Récupérer l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Lister les fichiers
        run: ls

  docker:
    runs-on: ubuntu-latest
    needs: download
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/exercice6spring .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/exercice6spring


