name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build the application
        run: |
          ./mvnw install -DskipTests
          ./mvnw package -DskipTests

      - name: Build message
        run: echo "Build of the application was successful!"
