name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout repo
       uses: actions/checkout@v4

     - name: set up jdk
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'adopt'

     - name: install dependencies
       run: ./mvnw install -DskipTests

     - name: build app
       run: ./mvnw package -DskipTests

     - name: Display build msg
       run: echo "Build Successful!"
